import "../globals.css";
import type { Metadata } from "next";
import Sidebar from "../../components/Sidebar/Sidebar";
import Header from "../../components/Header/Header";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen text-gray-800">
      <Sidebar />
      <main className="flex-1 p-6 bg-gray-50">
        <Header />

        <div className="flex bg-gradient-to-bl from-indigo-900 to-teal-500">
          {children}
        </div>
      </main>
    </div>
  );
}
