import "../../globals.css";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  auth,
  nextjsss
}: {
    auth: React.ReactNode;
  nextjsss: React.ReactNode;
}) {
  return (
    <div className="flex min-h-screen text-gray-800">
      
          {auth}
          {nextjsss}
        
    </div>
  );
}
